server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: verySecretKeyChangeMe1234567890
  expiration-ms: 86400000
